const data = {
  services: [
    {
      name: 'Church Performance',
      slug: 'church-performance',
      category: 'music',
      image: '/assets/images/joy.png',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description:
        ' "Introducing SIGA, a passionate and versatile music artistic team specializing in captivating performances for church programs. With 7 years of experience and a deep reverence for sacred music, SIGA brings a divine touch to every performance, creating a spiritually uplifting atmosphere that resonates with audiences.Known for taking people to spiritual relm, SIGA effortlessly combines heartfelt lyrics with soulful melodies, delivering powerful and soul-stirring performances that touch the hearts of listeners. Whether it/s leading worship, performing gospel hymns, or sharing original compositions inspired by faith, SIGA weaves together musical artistry and devotion, leaving a lasting impression on every listener.',
    },
    {
      name: 'Wedding Performance',
      slug: 'wedding-performance',
      category: 'music',
      image: '/assets/images/joy.png',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description: ' A Live Musical Performance like no other',
    },
    {
      name: 'Burial Performance',
      slug: 'burial-performance',
      category: 'music',
      image: '/assets/images/joy.png',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description: ' A Live Musical Performance like no other',
    },
    {
      name: 'General Performance',
      slug: 'general-performance',
      category: 'music',
      image: '/assets/images/joy.png',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description: ' A Live Musical Performance like no other',
    },
    {
      name: 'saxophone tutoring',
      slug: 'saxophone-tutoring',
      category: 'tutoring',
      image: '/assets/images/joy.png',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description: ' A Live Musical Performance like no other',
    },
    {
      name: 'Piano tutoring',
      slug: 'piano-tutoring',
      category: 'tutoring',
      image: '/assets/images/joy.png',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description: ' A Live Musical Performance like no other',
    },
    {
      name: 'drum turoring',
      slug: 'drum-tutoring',
      category: 'tutoring',
      image: '/assets/images/BeautifulImage.jpg',
      numReviews: 10,
      rating: 5,
      availability: 'yes',
      description: ' A Live Musical Performance like no other',
    },
  ],
}

export default data
